version '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
      POSTGRES_DB: purchase_manager
    ports:
    - "5432:5432"
    volumes:
      -db-data:/var/lib/postgresql/data

volumes:
  db-data: